export const FETCH_GLOBAL_DATA = "FETCH_GLOBAL_DATA";
export const FETCH_GLOBAL_DAILY_DATA = "FETCH_GLOBAL_DAILY_DATA";
export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRY_DATA = "FETCH_COUNTRY_DATA";
export const FETCH_INDIAN_DATA = "FETCH_INDIAN_DATA";

export const SELECT_COUNTRY = "SELECT_COUNTRY";

export const SELECT_INDIAN_STATE = "SELECT_INDIAN_STATE";
export const SELECT_INDIAN_DISTRICT = "SELECT_INDIAN_DISTRICT";

export const SHOW_GLOBAL_DATA = "SHOW_GLOBAL_DATA";
export const SHOW_COUNTRY_WISE_DATA = "SHOW_COUNTRY_WISE_DATA";
export const SHOW_INDIAN_DATA = "SHOW_INDIAN_DATA";

export const OPEN_SIDE_DRAWER = "OPEN_SIDE_DRAWER";
export const CLOSE_SIDE_DRAWER = "CLOSE_SIDE_DRAWER";

export const SECRECT_KEY_ENTERED = "SECRECT_KEY_ENTERED";
export const EMPTY_SECRET_KEY = "EMPTY_SECRET_KEY";

export const SHOW_MoHFW_TWEETS = "SHOW_MoHFW_TWEETS";
export const HIDE_MoHFW_TWEETS = "HIDE_MoHFW_TWEETS";

export const MODIFY_MoHFW_TWEETS_CLASS_NAME = "MODIFY_MoHFW_TWEETS_CLASS_NAME";